### ISSUE TITLE
Choose metalsmith collection from .md file

### ISSUE THREAD

**Issue by fracu** [metalsmith/collections#26]
I've been using Metalsmith static site generator for some time and I believe is a great tool. Now I started using metalsmith-collections plugin but I stumbled across this issue.

Given the case that I have two collections defined, for instance "en_news" and "sp_news" and the following news.hbt file:

``` javascript
<h1>{{title}}</h1>
{{contents}}

<ul>
    {{#each collections.en_news}}
        <li>
            <h3>{{this.title}}</h3>
            <article>{{this.contents}}</article>
        </li>
    {{/each}}
</ul>
```

Now in the .md file I want the collection to be either collection.en_news:

``` javascript

---
title: News
template: news.hbt
lang-collection: en_news

---
News in english language
```

...or collection.sp_news:

``` javascript

---
title: Noticias
template: news.hbt
lang-collection: sp_news

---
News in spanish language
```

How can I use "lang-collection" inside test.hbt to define the used collection?

Of course the following does not work:

``` javascript
{{#each collections.{{lang-collection}}}}
```

Thanks in advance!

**Comment by GRUBES** [comment]
@fracu I just accomplished this today using Handlebars' `lookup` helper:

My handlebars layout:
```html
{{#each (lookup collections rollup)}}
  <li>
    <h3><a href="{{../relative this.path }}">{{ this.title }}</a></h3>
    {{{ this.excerpt }}}
   </li>
{{/each}}
```
My yaml front-matter:
```yaml
---
title: Recent Articles
layout: rollup.html
rollup: recent-articles
associated-collection: articles
---
```
