### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by M-Pixel** [metalsmith/collections#30]
The documentation describes how to describe and ingest collections, but there is no explanation as to how the collections can be used in other files (such as in an index.jade).

**Comment by mgruesbeck** [comment]
theqwertman is right. Any examples of this?

**Comment by donmccurdy** [comment]
+1. An example of simply listing the posts in a collection would be extremely helpful.

**Comment by coffeenotfound** [comment]
Without an overview of the added properties this plugin is basically useless...

**Comment by woodyrew** [comment]
Greatly appreciate a PR for this.

**Comment by webketje** [comment]
Solved with release 1.2.0
