### ISSUE TITLE
Do not output collection files

### ISSUE THREAD

**Issue by toovy** [metalsmith/collections#31]
Hi,
in jekyll there is an option to ignore the output of collections. That means e.g. the collection can be used in template code, but the file is not written to the output directory.

See http://jekyllrb.com/docs/collections/:

```
collections:
    my_collection:
      output: false
```

Can this be achieved with metalsmith-collections?

**Comment by 1cgonza** [comment]
@toovy did you figure this out? I need to do exactly that.

**Comment by toovy** [comment]
@1cgonza I could not solve it, sorry. I just live with the output.

**Comment by 1cgonza** [comment]
I found a workaround for now using [metalsmith-drafts](https://github.com/segmentio/metalsmith-drafts). The drafts plugin needs to go after the collections plugin and it takes care of removing the files that have `draft: true` on the metadata.

```javascript
var collections  = require('metalsmith-collections');
var drafts = require('metalsmith-drafts');
// ...
.use(collections({})
.use(drafts())
// ...
```

It is not a very elegant solution, but this will work for me. I can get all the files while building an index page, and then they are ignored in the output.

**Comment by Oisota** [comment]
I achieved this by using [metalsmith-ignore](https://github.com/segmentio/metalsmith-ignore).
```javascript
.use(collections({
    posts: {
        pattern: 'posts/*',
    },
    projects: {
        pattern: 'projects/*',
    }
 }))
 .use(markdown())
 .use(ignore('projects/*'))
```
The  `posts/*` collection is generated as separate files while the `projects/*` collection is available to templates but does not get generated as files.

**Comment by webketje** [comment]
Closing this issue as there are enough ways to achieve this without adding additional functionality to the plugin
