### ISSUE TITLE
Documentation/Examples of Previous/Next functionality.

### ISSUE THREAD

**Issue by thiagodemellobueno** [metalsmith/collections#33]
Examples of how to implement previous/next functionality in templates would be greatly appreciated.

**Comment by nikmartin** [comment]
I know this isn't a substitute for good docs, but the previous/next functionality is very simple.once the collection is built, the plugin just loops through the collection, adding a prev and next property to the file metadata, which is just the name of the previous and next file in the list of files I the collection.

**Comment by spsaucier** [comment]
In case others are seeing `[Object object]` when you try to use the above, try this instead:

```html
    <div class="lesson-nav">
      {{#if previous}}
        <a class="prev" href="/{{{previous.url}}}">&larr; {{{previous.title}}}</a>
      {{/if}}
      {{#if next}}
        <a class="next right" href="/{{{next.url}}}">{{{next.title}}} &rarr;</a>
      {{/if}}
    </div>
```

**Comment by alexandrubau** [comment]
+1
