### ISSUE TITLE
index example?

### ISSUE THREAD

**Issue by jbenet** [metalsmith/collections#36]
would be nice if readme included an example of generating index pages.

**Comment by woodyrew** [comment]
I started working on this and decided it was outside of the scope of the plugin as it's best achieved `metalsmith-layouts`.  Have a read of this tutorial that explains [link structure and using collections in templates](http://www.robinthrift.com/posts/metalsmith-part-2-shaping-the-metal/#link-structure).

**Comment by donmccurdy** [comment]
Link above gone, should be this i assume: http://robinthrift.com/post/metalsmith-part-2-shaping-the-metal/

**Comment by webketje** [comment]
Provided in the readme since 1.2.0
