### ISSUE TITLE
Order of plugins?

### ISSUE THREAD

**Issue by dy** [metalsmith/collections#37]
Hello!
I have a simple config:

``` json
{
  "source": "./content",
  "destination": "./_site",
  "metadata": {
    "title": "title",
    "description": "desc"
  },
  "plugins": {
    "metalsmith-drafts": {},
    "metalsmith-markdown": {},
    "metalsmith-permalinks": {
      "pattern": ":title"
    },
    "metalsmith-templates": {
      "engine": "swig",
      "directory": "templates"
    },
    "metalsmith-collections": {
      "genre": {}
    }
  }
}
```

If I try to build it `$ metalsmith`, I can’t get `collections` variable from within templates.
Maybe there should be some docs on basic usage of collections in templates?

**Comment by dfcreative** [comment]
Done this via `build.js` script - same result. There’s no `collections` data in templates.
```js
var Metalsmith = require('metalsmith');
var drafts = require('metalsmith-drafts');
var markdown = require('metalsmith-markdown');
var permalinks = require('metalsmith-permalinks');
var templates = require('metalsmith-templates');
var collections = require('metalsmith-collections');


var ms = Metalsmith(__dirname)
	.source('./content')
	.destination('./_site')
	.use(drafts())
	.use(collections())
	.use(markdown())
	.use(permalinks(':title'))
	.use(templates({
		engine: 'swig',
		directory: 'templates'
	}));


ms.build(function(err) {
	if (err) throw err;
});

```

**Comment by dfcreative** [comment]
Hello! @travisjeffery @tj @lancejpollard 
Any response? How can I contribute? I’m not skilled enough to catch the problem. Seems it happens somewhere in the depth of metalsmith/ware/thunkify.

**Comment by dfcreative** [comment]
Wow. Simple changing the "order" of plugins in config solved the issue.
```js
"plugins": {
    "metalsmith-collections": {},
    "metalsmith-drafts": {},
    "metalsmith-markdown": {},
    "metalsmith-permalinks": {
      "pattern": ":title"
    },
    "metalsmith-templates": {
      "engine": "swig",
      "directory": "templates"
    }
  }
```

**Comment by dfcreative** [comment]
Now I get ∞ recursion in swig, just trying to print `{{ collections }}` in template

**Comment by snuggles08** [comment]
@dfcreative 2nd issue is separate, first is because the collections are generated after they're used.

**Comment by MegaJ** [comment]
@dfcreative Your second error is probably because collections has nested elements that refer to themselves. I'm gussing swig might be doing something like a `JSON.stringify()`, which errors out in such cases.

Are you still using metalsmith?

**Comment by webketje** [comment]
Closing as stale and insufficient debug info
