### ISSUE TITLE
Inconstant contents

### ISSUE THREAD

**Issue by jondashkyle** [metalsmith/collections#4]
Hey—unsure if this is a problem related to Metalsmith or this plugin. When I build the site the value of contents for each article sometimes changes.

For example, here's the value of contents of article one:
`<p>A really short, rushed-feeling string of words.</p>`

However, when I edit article two by adding a couple line breaks, the contents of article one becomes:

`<html> <head> <title>My Blog</title> </head> <body> <h1>My Fourth Post</h1> <time>Thu Dec 06 2012 16:00:00 GMT-0800 (PST)</time> <p>A really short, rushed-feeling string of words.</p> </body> </html>`

Any ideas?

**Comment by rgladwell** [comment]
This still seems to be a problem with the latest versions of metalsmith/metalsmith-collections. I'm not using metalsmith-templates.

The value of `{{{ contents }}}` seem to change during different runs, possibly due to a thread/timing issue.
