### ISSUE TITLE
Self closing tags stripped out / removed?

### ISSUE THREAD

**Issue by oller** [metalsmith/collections#56]
I'm using metalsmith to render some SVG markup, which contain a lot of self closing tags:

For example:

``` svg
 <circle cx="33" cy="19" r="2"/>
```

When printing these out at the layout level with metalsmith there is no problem, everything is preserved.

However when I'm looping through a collection:

**index.html**

``` js
        {{#each collections.components }}
{{>component}}
        {{/each}}
```

**component.html**

``` js
    <div class="demo-rendered cf">
        {{{ this.contents }}}
    </div>
```

**output**

``` html
    <div class="demo-rendered cf">
         <circle cx="33" cy="19" r="2">
    </div>
```

All the self-closing tags are stripped out, which means the browser assumes these tags need nesting and everything goes downhill pretty quickly.

The fact these are only removed when returning from the collection implies the issue is with this plugin.  Is this something anyone else has run into?

(note this also applies to more basic self closing tags: `<br/>`, `<input type="text />`

**Comment by webketje** [comment]
Pretty sure this has nothing to do with collections, collections does not touch a file's `contents`
