### ISSUE TITLE
How to use collections with ignore?

### ISSUE THREAD

**Issue by julmot** [metalsmith/collections#58]
I am having a one-page that should include some collections. But, I don't want to generate those include files. So I am using `.ignore("mypath")` like described in [the docs](https://github.com/metalsmith/metalsmith#ignorepath). However, when using `ignore` after or before using `collections`, those include files will be deleted from the stack of the collection. So, how can I use `ignore` but still get even ignored files into the stack of `collections`?

I am aware that this repository is not actively maintained, so in the meantime I will either don't use this plugin or delete the ignore files after using metalsmith.

**Comment by GRUBES** [comment]
Just adding my voice as I'm struggling with this, too. Would like to be able to basically say "Add all of markdown files in folder `abc` *except* files named `blah`".

Was trying to employ some of the concepts described [here](https://github.com/isaacs/minimatch/issues/65) but didn't get anything to stick.

**Comment by andreasvirkus** [comment]
It's an old issue, but for any future searchers, you can exclude them like this under `pattern`:
```
.use(collections({
    pages: {
        pattern: '*(!cv).md',
    }
}))
```
So now I have a `pages` collection with every Markdown file under `src/`, except my `cv.md` file.

**Comment by webketje** [comment]
`Metalsmith.ignore` always executes before any plugins run. Use [`@metalsmith/remove`](https://github.com/metalsmith/remove) to remove files *after* they have been used by other plugins. As for excluding certain files inside a same folder, you would use a negated pattern along with a regular glob pattern, like so: `['abc/**/*.md', '!abc/blah.md']`
