### ISSUE TITLE
Add metadata to every file in a collection

### ISSUE THREAD

**Issue by nathanboktae** [metalsmith/collections#59]
Is there a way to do this currently? I don't see a way.

I'd be glad to send a PR to do this if desired.

**Comment by jegtnes** [comment]
Initially I thought this was what [collection metadata](https://github.com/segmentio/metalsmith-collections#collection-metadata) did but I could not for the life of me get that to work. If you have some time to do this there's at least one other person who'd appreciate it 🤘🏻

**Comment by nathanboktae** [comment]
Yeah after digging more into Metalsmith and running into even bigger problems I realized it's a poor implementation of gulp so I switched to gulp and I'm good, so sorry there will be no PR coming.

**Comment by rbardini** [comment]
I've just published [metalsmith-collection-metadata](https://github.com/rbardini/metalsmith-collection-metadata) to handle this exact problem, if anyone is interested.

**Comment by webketje** [comment]
This can also easily be done with https://github.com/dpobel/metalsmith-filemetadata
