### ISSUE TITLE
Can't get prev or next links

### ISSUE THREAD

**Issue by abhijeetvramgir** [metalsmith/collections#65]
I have to md files:

```

---
title: English
collection: articles
layout: article.hbs

---
```

```

---
title: Hindi
collection: articles
layout: article.hbs

---
```

  I'm matching using the `collection` metadata. How do I get the links for the pages??
Thanks!

**Comment by webketje** [comment]
This can easily be done (for example with Handlebars) as:

```hbs
{{ article.previous.path }}
```
Bear in mind that if you `use'd` collections before eg layouts plugin, the file metadata `path` will contain the template language extension and you need to replace the extension with, eg `.html`.

See for example the custom plugin below, between `collections` & `layouts`

```js
Metalsmith(__dirname)
  .use(collections())
  .use((files) => {
     Object.entries(files).forEach(([file, path]) => {
       file.path = path.replace(/\.hbs$/, '.html')
     })
  })
  .use(layouts())
```
