### ISSUE TITLE
Absence of metadata in output in non-empty collections

### ISSUE THREAD

**Issue by tortilaman** [metalsmith/collections#76]
Adding metadata to a collection works fine, but as soon as that collection has any items in it, all the metadata goes away.

**Scenario 1 - Empty collection with Metadata:**
_Config:_
```
"posts": {
          "sortBy": "date",
          "reverse": false,
          "metadata": {
            "name": "Posts",
            "path": "posts/index.html"
          }
}
```
_Metadata:_
```
posts: {
    name: "Posts",
    path: "posts/index.html
}
```
**Scenario 2 - Using pattern with metadata:**
_Config:_
```
"posts": {
          "pattern": "posts/**.md",
          "sortBy": "date",
          "reverse": false,
          "metadata": {
            "name": "Posts",
            "path": "posts/index.html"
          }
}
```
_Metadata:_
Posts data without a `metadata` tag.

This is also an issue when using post metadata to define collections.

**Comment by webketje** [comment]
@tortilaman does this issue still persist for you? I think it should be good with the latest release

**Comment by webketje** [comment]
Closing as stale
