### ISSUE TITLE
Metadata for documents contains markdown

### ISSUE THREAD

**Issue by jcrawford** [metalsmith/collections#88]
When running metalsmith-collections I have found that `metadata.collections['collection_name']` each document contains markdown.

I have written a plugin to index the data into Algolia and this is what led me to the discovery.

You can see my `search.js` plugin functionality [here](https://github.com/jcrawford/jcrawford.github.io/blob/develop/lib/search.js#L45) and my build.js file [here](https://github.com/jcrawford/jcrawford.github.io/blob/develop/build.js#L58)

As can be seen with the following screenshot you can see there is markdown in the data being sent to Algolia, any assistance with information on why this would be happening would be great.

<img width="738" alt="screen shot 2018-12-31 at 10 42 03 am" src="https://user-images.githubusercontent.com/875341/50565120-8fc5b680-0cf9-11e9-8b9d-edc32a7aa097.png">

It is my belief that `metalsmith-in-place` is not replacing the markdown in the `metadata.collections` data structure, everything I have seen showed that collections should
be run before in-place, is it actually the opposite?  When I try to run in-place before collections when I access the `metadata.collections['collection_name']` I get 0 documents found.

**Comment by webketje** [comment]
Closing this issue as the repo is now using Gatsby
