### ISSUE TITLE
please update npm repo

### ISSUE THREAD

**Issue by matbrgz** [metalsmith/collections#91]
On https://www.npmjs.com/package/metalsmith-collections latest is on 0.9.0 not 1.0.0.

**Comment by davidjgoss** [comment]
Workaround for the meantime:

```
$ npm install git@github.com:segmentio/metalsmith-collections.git#v1.0.0
```

But not ideal...

**Comment by kowitz** [comment]
Yes, please update npm to include v1.0.0. The documentation includes `filterBy`, but this feature is not available via the latest v0.9.0 npm package.

**Comment by tubia** [comment]
As @kowitz said, we need the `filterBy` feature. People are still suffering while using all of this.

**Comment by webketje** [comment]
Now published to https://npmjs.com/package/@metalsmith/collections
